server.port=8084
spring.application.name=gateway

# Disable Eureka in Kubernetes (we use K8s services for routing)
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Redis inside K8s
spring.data.redis.host=redis
spring.data.redis.port=6379

# Zipkin inside K8s
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.tracing.sampling.probability=1.0

# Gateway Routes using Kubernetes Services on Port 80
spring.cloud.gateway.routes[0].id=company_service
spring.cloud.gateway.routes[0].uri=http://company:80
spring.cloud.gateway.routes[0].predicates[0]=Path=/companies/**
spring.cloud.gateway.routes[0].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.replenishRate=10
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=20
spring.cloud.gateway.routes[0].filters[0].args.key-resolver=#{@ipKeyResolver}

spring.cloud.gateway.routes[1].id=job_service
spring.cloud.gateway.routes[1].uri=http://job:80
spring.cloud.gateway.routes[1].predicates[0]=Path=/jobs/**
spring.cloud.gateway.routes[1].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[1].filters[0].args.redis-rate-limiter.replenishRate=10
spring.cloud.gateway.routes[1].filters[0].args.redis-rate-limiter.burstCapacity=20
spring.cloud.gateway.routes[1].filters[0].args.key-resolver=#{@ipKeyResolver}

spring.cloud.gateway.routes[2].id=review_service
spring.cloud.gateway.routes[2].uri=http://review:80
spring.cloud.gateway.routes[2].predicates[0]=Path=/reviews/**
spring.cloud.gateway.routes[2].filters[0].name=RequestRateLimiter
spring.cloud.gateway.routes[2].filters[0].args.redis-rate-limiter.replenishRate=10
spring.cloud.gateway.routes[2].filters[0].args.redis-rate-limiter.burstCapacity=20
spring.cloud.gateway.routes[2].filters[0].args.key-resolver=#{@ipKeyResolver}

# Setting log levels
logging.level.root=info
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE
